export type DiagramNodeTone =
  | 'signal'
  | 'memory'
  | 'skill'
  | 'agent'
  | 'harness'
  | 'foundation'
  | 'artifact'
  | 'metric'

export type DiagramEdgeTone = 'default' | 'feedback' | 'muted'
export type DiagramAnchor = 'top' | 'right' | 'bottom' | 'left'

export type DiagramZone = {
  id: string
  label: string
  x: number
  y: number
  width: number
  height: number
  fill: string
  stroke: string
  textColor: string
}

export type DiagramNode = {
  id: string
  label: string
  detail?: string
  x: number
  y: number
  width: number
  height: number
  tone: DiagramNodeTone
}

export type DiagramEdge = {
  from: string
  to: string
  fromSide?: DiagramAnchor
  toSide?: DiagramAnchor
  label?: string
  dashed?: boolean
  tone?: DiagramEdgeTone
  waypoints?: Array<{ x: number; y: number }>
}

export type BrainDiagram = {
  slug: string
  eyebrow: string
  title: string
  description: string
  width: number
  height: number
  zones: DiagramZone[]
  nodes: DiagramNode[]
  edges: DiagramEdge[]
}

export const BRAIN_DIAGRAMS: BrainDiagram[] = [
  {
    slug: 'thin-harness-fat-skills',
    eyebrow: 'Article Thesis',
    title: 'Thin Harness, Fat Skills',
    description:
      'The model logic moves up into reusable skill files, the harness stays small, and deterministic systems own trust-critical execution.',
    width: 1120,
    height: 420,
    zones: [
      {
        id: 'skills-band',
        label: 'Fat Skills',
        x: 40,
        y: 28,
        width: 1040,
        height: 102,
        fill: '#f5ead7',
        stroke: '#caa36b',
        textColor: '#8a5722',
      },
      {
        id: 'harness-band',
        label: 'Thin Harness',
        x: 92,
        y: 156,
        width: 936,
        height: 84,
        fill: '#ece9ff',
        stroke: '#8277dd',
        textColor: '#4f46b8',
      },
      {
        id: 'foundation-band',
        label: 'Deterministic Foundation',
        x: 40,
        y: 270,
        width: 1040,
        height: 114,
        fill: '#e8f3e7',
        stroke: '#6b9a70',
        textColor: '#335f3a',
      },
    ],
    nodes: [
      {
        id: 'enrichment-skill',
        label: 'Project Enrichment',
        detail: 'diarize + refresh pages',
        x: 68,
        y: 54,
        width: 214,
        height: 56,
        tone: 'skill',
      },
      {
        id: 'roadmap-skill',
        label: 'Roadmap Synthesis',
        detail: 'judge what matters',
        x: 312,
        y: 54,
        width: 222,
        height: 56,
        tone: 'skill',
      },
      {
        id: 'prd-skill',
        label: 'PRD Author',
        detail: 'repo-aware planning',
        x: 568,
        y: 54,
        width: 222,
        height: 56,
        tone: 'skill',
      },
      {
        id: 'impact-skill',
        label: 'Impact Review',
        detail: 'measure + codify',
        x: 824,
        y: 54,
        width: 228,
        height: 56,
        tone: 'skill',
      },
      {
        id: 'resolver',
        label: 'Resolver',
        detail: 'task -> pages',
        x: 164,
        y: 174,
        width: 220,
        height: 48,
        tone: 'harness',
      },
      {
        id: 'context-loader',
        label: 'Context Loader',
        detail: 'fetch exact inputs',
        x: 450,
        y: 174,
        width: 220,
        height: 48,
        tone: 'harness',
      },
      {
        id: 'run-logger',
        label: 'Run Logger',
        detail: 'audit + writeback',
        x: 736,
        y: 174,
        width: 220,
        height: 48,
        tone: 'harness',
      },
      {
        id: 'query-db',
        label: 'Query DB',
        detail: 'SQL / filters',
        x: 68,
        y: 304,
        width: 170,
        height: 56,
        tone: 'foundation',
      },
      {
        id: 'search-index',
        label: 'Search',
        detail: 'keyword / vector',
        x: 270,
        y: 304,
        width: 170,
        height: 56,
        tone: 'foundation',
      },
      {
        id: 'policy-engine',
        label: 'Policy Engine',
        detail: 'rank / safety / caps',
        x: 472,
        y: 304,
        width: 188,
        height: 56,
        tone: 'foundation',
      },
      {
        id: 'repo-readers',
        label: 'Repo Readers',
        detail: 'docs + file map',
        x: 706,
        y: 304,
        width: 176,
        height: 56,
        tone: 'foundation',
      },
      {
        id: 'queue-system',
        label: 'Queues',
        detail: 'jobs + webhooks',
        x: 918,
        y: 304,
        width: 134,
        height: 56,
        tone: 'foundation',
      },
    ],
    edges: [
      {
        from: 'enrichment-skill',
        to: 'resolver',
        fromSide: 'bottom',
        toSide: 'top',
      },
      {
        from: 'roadmap-skill',
        to: 'resolver',
        fromSide: 'bottom',
        toSide: 'top',
        waypoints: [{ x: 423, y: 128 }],
      },
      {
        from: 'prd-skill',
        to: 'context-loader',
        fromSide: 'bottom',
        toSide: 'top',
      },
      {
        from: 'impact-skill',
        to: 'run-logger',
        fromSide: 'bottom',
        toSide: 'top',
      },
      {
        from: 'resolver',
        to: 'context-loader',
        fromSide: 'right',
        toSide: 'left',
        label: 'route',
      },
      {
        from: 'context-loader',
        to: 'run-logger',
        fromSide: 'right',
        toSide: 'left',
        label: 'hydrate',
      },
      {
        from: 'resolver',
        to: 'query-db',
        fromSide: 'bottom',
        toSide: 'top',
      },
      {
        from: 'resolver',
        to: 'search-index',
        fromSide: 'bottom',
        toSide: 'top',
        waypoints: [{ x: 354, y: 256 }],
      },
      {
        from: 'context-loader',
        to: 'policy-engine',
        fromSide: 'bottom',
        toSide: 'top',
      },
      {
        from: 'context-loader',
        to: 'repo-readers',
        fromSide: 'bottom',
        toSide: 'top',
        waypoints: [{ x: 624, y: 256 }],
      },
      {
        from: 'run-logger',
        to: 'queue-system',
        fromSide: 'bottom',
        toSide: 'top',
      },
    ],
  },
  {
    slug: 'today-vs-v1',
    eyebrow: 'Architecture Delta',
    title: 'Today vs. Project Brain v1',
    description:
      'The current system jumps from raw signals into one-shot synthesis. V1 inserts compiled truth pages, resolver routing, and deterministic checks.',
    width: 1120,
    height: 430,
    zones: [
      {
        id: 'today-lane',
        label: 'Today',
        x: 40,
        y: 42,
        width: 484,
        height: 320,
        fill: '#fff2e7',
        stroke: '#d6a779',
        textColor: '#91592a',
      },
      {
        id: 'v1-lane',
        label: 'Project Brain v1',
        x: 596,
        y: 42,
        width: 484,
        height: 320,
        fill: '#edf5ff',
        stroke: '#7b95c9',
        textColor: '#35527e',
      },
    ],
    nodes: [
      {
        id: 'signals-today',
        label: 'Signals',
        detail: 'raw feedback',
        x: 78,
        y: 150,
        width: 112,
        height: 56,
        tone: 'signal',
      },
      {
        id: 'one-shot-prompt',
        label: 'One-Shot Prompt',
        detail: 'summary + synthesis',
        x: 228,
        y: 150,
        width: 142,
        height: 56,
        tone: 'harness',
      },
      {
        id: 'roadmap-prds-today',
        label: 'Roadmap + PRDs',
        detail: 'acts as memory',
        x: 408,
        y: 102,
        width: 114,
        height: 58,
        tone: 'artifact',
      },
      {
        id: 'build-jobs-today',
        label: 'Build Jobs',
        detail: 'freeform prompt',
        x: 408,
        y: 242,
        width: 114,
        height: 58,
        tone: 'artifact',
      },
      {
        id: 'signals-v1',
        label: 'Signals',
        detail: 'append-only log',
        x: 630,
        y: 150,
        width: 112,
        height: 56,
        tone: 'signal',
      },
      {
        id: 'project-brain',
        label: 'Project Brain',
        detail: 'pages + versions + citations',
        x: 780,
        y: 118,
        width: 168,
        height: 102,
        tone: 'memory',
      },
      {
        id: 'resolver-v1',
        label: 'Resolver',
        detail: 'select context',
        x: 976,
        y: 74,
        width: 92,
        height: 52,
        tone: 'harness',
      },
      {
        id: 'skill-v1',
        label: 'Skill',
        detail: 'judge',
        x: 976,
        y: 150,
        width: 92,
        height: 52,
        tone: 'skill',
      },
      {
        id: 'checks-v1',
        label: 'Checks',
        detail: 'rank + guard',
        x: 976,
        y: 226,
        width: 92,
        height: 52,
        tone: 'foundation',
      },
      {
        id: 'artifacts-v1',
        label: 'Briefs / PRDs / Jobs',
        detail: 'projection, not memory',
        x: 780,
        y: 266,
        width: 168,
        height: 58,
        tone: 'artifact',
      },
    ],
    edges: [
      {
        from: 'signals-today',
        to: 'one-shot-prompt',
        fromSide: 'right',
        toSide: 'left',
      },
      {
        from: 'one-shot-prompt',
        to: 'roadmap-prds-today',
        fromSide: 'right',
        toSide: 'left',
        waypoints: [{ x: 390, y: 178 }, { x: 390, y: 131 }],
      },
      {
        from: 'one-shot-prompt',
        to: 'build-jobs-today',
        fromSide: 'right',
        toSide: 'left',
        waypoints: [{ x: 390, y: 178 }, { x: 390, y: 271 }],
      },
      {
        from: 'signals-v1',
        to: 'project-brain',
        fromSide: 'right',
        toSide: 'left',
      },
      {
        from: 'project-brain',
        to: 'resolver-v1',
        fromSide: 'right',
        toSide: 'left',
        waypoints: [{ x: 958, y: 135 }, { x: 958, y: 100 }],
      },
      {
        from: 'resolver-v1',
        to: 'skill-v1',
        fromSide: 'bottom',
        toSide: 'top',
      },
      {
        from: 'skill-v1',
        to: 'checks-v1',
        fromSide: 'bottom',
        toSide: 'top',
      },
      {
        from: 'checks-v1',
        to: 'artifacts-v1',
        fromSide: 'left',
        toSide: 'right',
        waypoints: [{ x: 958, y: 252 }, { x: 958, y: 295 }],
      },
      {
        from: 'skill-v1',
        to: 'project-brain',
        fromSide: 'left',
        toSide: 'right',
        tone: 'feedback',
        dashed: true,
        label: 'write back',
        waypoints: [{ x: 960, y: 176 }],
      },
    ],
  },
  {
    slug: 'resolver-learning-loop',
    eyebrow: 'Resolver + Learning',
    title: 'Resolver Path and Compounding Loop',
    description:
      'Resolvers load the right context for the current task, skills execute with that context, and post-ship review writes improvements back into the skill and rule system.',
    width: 1120,
    height: 460,
    zones: [
      {
        id: 'resolve-zone',
        label: 'Resolve',
        x: 30,
        y: 40,
        width: 380,
        height: 360,
        fill: '#fff5ea',
        stroke: '#d7ab7e',
        textColor: '#91592a',
      },
      {
        id: 'run-zone',
        label: 'Run',
        x: 430,
        y: 40,
        width: 320,
        height: 360,
        fill: '#f2f0ff',
        stroke: '#8980e0',
        textColor: '#4c43b1',
      },
      {
        id: 'learn-zone',
        label: 'Learn',
        x: 770,
        y: 40,
        width: 320,
        height: 360,
        fill: '#eef7f3',
        stroke: '#78a287',
        textColor: '#2f6240',
      },
    ],
    nodes: [
      {
        id: 'task-request',
        label: 'Task Request',
        detail: 'generate PRD',
        x: 62,
        y: 180,
        width: 138,
        height: 58,
        tone: 'signal',
      },
      {
        id: 'resolver-rules',
        label: 'Resolver Rules',
        detail: 'which pages load',
        x: 252,
        y: 88,
        width: 154,
        height: 60,
        tone: 'harness',
      },
      {
        id: 'context-pages',
        label: 'Context Pages',
        detail: 'overview + repo + safety',
        x: 252,
        y: 258,
        width: 154,
        height: 74,
        tone: 'memory',
      },
      {
        id: 'skill-file',
        label: 'Skill File',
        detail: 'markdown procedure',
        x: 476,
        y: 88,
        width: 156,
        height: 60,
        tone: 'skill',
      },
      {
        id: 'skill-run',
        label: 'Skill Invocation',
        detail: 'read + judge + write',
        x: 476,
        y: 236,
        width: 180,
        height: 82,
        tone: 'skill',
      },
      {
        id: 'output',
        label: 'Output Artifact',
        detail: 'PRD / roadmap / scan',
        x: 776,
        y: 172,
        width: 150,
        height: 60,
        tone: 'artifact',
      },
      {
        id: 'actual-metrics',
        label: 'Actual Metrics',
        detail: 'did it work?',
        x: 954,
        y: 88,
        width: 120,
        height: 58,
        tone: 'metric',
      },
      {
        id: 'impact-review',
        label: 'Impact Review',
        detail: 'codify what changed',
        x: 940,
        y: 254,
        width: 148,
        height: 76,
        tone: 'skill',
      },
    ],
    edges: [
      {
        from: 'task-request',
        to: 'resolver-rules',
        fromSide: 'right',
        toSide: 'left',
        waypoints: [{ x: 226, y: 209 }, { x: 226, y: 118 }],
      },
      {
        from: 'task-request',
        to: 'skill-file',
        fromSide: 'right',
        toSide: 'left',
        tone: 'muted',
        dashed: true,
        waypoints: [{ x: 226, y: 209 }, { x: 226, y: 118 }, { x: 450, y: 118 }],
      },
      {
        from: 'resolver-rules',
        to: 'context-pages',
        fromSide: 'bottom',
        toSide: 'top',
        label: 'load',
      },
      {
        from: 'context-pages',
        to: 'skill-run',
        fromSide: 'right',
        toSide: 'left',
      },
      {
        from: 'skill-file',
        to: 'skill-run',
        fromSide: 'bottom',
        toSide: 'top',
      },
      {
        from: 'skill-run',
        to: 'output',
        fromSide: 'right',
        toSide: 'left',
        label: 'emit',
      },
      {
        from: 'output',
        to: 'actual-metrics',
        fromSide: 'right',
        toSide: 'left',
        tone: 'muted',
        dashed: true,
        waypoints: [{ x: 942, y: 202 }, { x: 942, y: 117 }],
      },
      {
        from: 'actual-metrics',
        to: 'impact-review',
        fromSide: 'bottom',
        toSide: 'top',
      },
      {
        from: 'impact-review',
        to: 'skill-file',
        fromSide: 'left',
        toSide: 'right',
        tone: 'feedback',
        dashed: true,
        label: 'codify',
        waypoints: [{ x: 914, y: 292 }, { x: 914, y: 118 }, { x: 650, y: 118 }],
      },
      {
        from: 'impact-review',
        to: 'resolver-rules',
        fromSide: 'left',
        toSide: 'right',
        tone: 'feedback',
        dashed: true,
        label: 'retune',
        waypoints: [{ x: 914, y: 292 }, { x: 914, y: 366 }, { x: 430, y: 366 }, { x: 430, y: 118 }],
      },
    ],
  },
  {
    slug: 'always-on-head-of-product-agent',
    eyebrow: 'Always-On Agent',
    title: 'OpenClaw-Style Head of Product Interface',
    description:
      'An always-on Head of Product agent would sit on top of the project brain, watch every product and repo signal, decide what matters, and continuously push work into human review, roadmap generation, and implementation queues.',
    width: 1120,
    height: 470,
    zones: [
      {
        id: 'observe-zone',
        label: 'Observe',
        x: 28,
        y: 42,
        width: 230,
        height: 372,
        fill: '#fff5ea',
        stroke: '#d7ab7e',
        textColor: '#91592a',
      },
      {
        id: 'decide-zone',
        label: 'Decide',
        x: 278,
        y: 42,
        width: 334,
        height: 372,
        fill: '#f2f0ff',
        stroke: '#8980e0',
        textColor: '#4c43b1',
      },
      {
        id: 'act-zone',
        label: 'Act',
        x: 632,
        y: 42,
        width: 250,
        height: 372,
        fill: '#eef7f3',
        stroke: '#78a287',
        textColor: '#2f6240',
      },
      {
        id: 'steward-zone',
        label: 'Steward',
        x: 902,
        y: 42,
        width: 190,
        height: 372,
        fill: '#fff1f6',
        stroke: '#c77f9e',
        textColor: '#7f3553',
      },
    ],
    nodes: [
      {
        id: 'event-stream',
        label: 'Signals + Telemetry',
        detail: 'feedback / analytics / scans',
        x: 52,
        y: 98,
        width: 184,
        height: 72,
        tone: 'signal',
      },
      {
        id: 'repo-watch',
        label: 'Repo + Shipping Watch',
        detail: 'PRs / incidents / metrics',
        x: 52,
        y: 238,
        width: 184,
        height: 72,
        tone: 'metric',
      },
      {
        id: 'project-brain-hub',
        label: 'Project Brain',
        detail: 'pages / versions / citations',
        x: 308,
        y: 86,
        width: 166,
        height: 86,
        tone: 'memory',
      },
      {
        id: 'skills-rules',
        label: 'Skills + Rules',
        detail: 'product policy / procedures',
        x: 308,
        y: 238,
        width: 166,
        height: 74,
        tone: 'skill',
      },
      {
        id: 'resolver-agent',
        label: 'Resolver',
        detail: 'load exact context',
        x: 504,
        y: 94,
        width: 92,
        height: 52,
        tone: 'harness',
      },
      {
        id: 'hop-agent',
        label: 'Always-On HoP Agent',
        detail: 'triage / decide / delegate',
        x: 450,
        y: 176,
        width: 152,
        height: 96,
        tone: 'agent',
      },
      {
        id: 'roadmap-backlog',
        label: 'Roadmap + Briefs',
        detail: 'what should happen next',
        x: 664,
        y: 82,
        width: 188,
        height: 62,
        tone: 'artifact',
      },
      {
        id: 'digest-alerts',
        label: 'Digest + Alerts',
        detail: 'what needs attention now',
        x: 664,
        y: 176,
        width: 188,
        height: 62,
        tone: 'artifact',
      },
      {
        id: 'implementation-queue',
        label: 'Implementation Queue',
        detail: 'PRD / issue / build packet',
        x: 664,
        y: 270,
        width: 188,
        height: 62,
        tone: 'artifact',
      },
      {
        id: 'human-review',
        label: 'Human Review',
        detail: 'approve / redirect / veto',
        x: 936,
        y: 108,
        width: 124,
        height: 58,
        tone: 'artifact',
      },
      {
        id: 'learning-loop',
        label: 'Learning Loop',
        detail: 'measure / refine / retune',
        x: 926,
        y: 244,
        width: 144,
        height: 74,
        tone: 'agent',
      },
    ],
    edges: [
      {
        from: 'event-stream',
        to: 'project-brain-hub',
        fromSide: 'right',
        toSide: 'left',
        label: 'ingest',
      },
      {
        from: 'repo-watch',
        to: 'project-brain-hub',
        fromSide: 'right',
        toSide: 'left',
        waypoints: [{ x: 272, y: 274 }, { x: 272, y: 150 }],
      },
      {
        from: 'project-brain-hub',
        to: 'resolver-agent',
        fromSide: 'right',
        toSide: 'left',
        label: 'resolve',
      },
      {
        from: 'project-brain-hub',
        to: 'hop-agent',
        fromSide: 'right',
        toSide: 'left',
        tone: 'muted',
        dashed: true,
        label: 'memory sync',
        waypoints: [{ x: 486, y: 128 }, { x: 486, y: 224 }],
      },
      {
        from: 'skills-rules',
        to: 'hop-agent',
        fromSide: 'right',
        toSide: 'left',
        label: 'steer',
      },
      {
        from: 'resolver-agent',
        to: 'hop-agent',
        fromSide: 'bottom',
        toSide: 'top',
      },
      {
        from: 'hop-agent',
        to: 'roadmap-backlog',
        fromSide: 'right',
        toSide: 'left',
        label: 'prioritize',
        waypoints: [{ x: 636, y: 224 }, { x: 636, y: 113 }],
      },
      {
        from: 'hop-agent',
        to: 'digest-alerts',
        fromSide: 'right',
        toSide: 'left',
        label: 'notify',
      },
      {
        from: 'hop-agent',
        to: 'implementation-queue',
        fromSide: 'right',
        toSide: 'left',
        label: 'dispatch',
        waypoints: [{ x: 636, y: 224 }, { x: 636, y: 301 }],
      },
      {
        from: 'hop-agent',
        to: 'human-review',
        fromSide: 'right',
        toSide: 'left',
        tone: 'muted',
        dashed: true,
        label: 'escalate',
        waypoints: [{ x: 620, y: 224 }, { x: 902, y: 224 }, { x: 902, y: 137 }],
      },
      {
        from: 'human-review',
        to: 'learning-loop',
        fromSide: 'bottom',
        toSide: 'top',
      },
      {
        from: 'repo-watch',
        to: 'learning-loop',
        fromSide: 'right',
        toSide: 'left',
        tone: 'muted',
        dashed: true,
        label: 'actuals',
        waypoints: [{ x: 272, y: 274 }, { x: 900, y: 274 }],
      },
      {
        from: 'learning-loop',
        to: 'skills-rules',
        fromSide: 'left',
        toSide: 'right',
        tone: 'feedback',
        dashed: true,
        label: 'codify',
        waypoints: [{ x: 900, y: 281 }, { x: 492, y: 281 }],
      },
      {
        from: 'learning-loop',
        to: 'project-brain-hub',
        fromSide: 'left',
        toSide: 'right',
        tone: 'feedback',
        dashed: true,
        label: 'refresh',
        waypoints: [{ x: 900, y: 281 }, { x: 900, y: 360 }, { x: 494, y: 360 }, { x: 494, y: 129 }],
      },
    ],
  },
  {
    slug: 'hop-agent-runtime-control-plane',
    eyebrow: 'Runtime Control Plane',
    title: 'HoP Agent Runtime: Cron vs. Webhook vs. Approval',
    description:
      'The always-on Head of Product agent should wake up from two sources only: scheduled sweeps and event-driven webhooks. It can draft autonomously, but anything that changes roadmap commitments or kicks off implementation should pass through explicit approval gates.',
    width: 1120,
    height: 490,
    zones: [
      {
        id: 'cron-zone',
        label: 'Cron',
        x: 28,
        y: 42,
        width: 218,
        height: 390,
        fill: '#fff5ea',
        stroke: '#d7ab7e',
        textColor: '#91592a',
      },
      {
        id: 'webhook-zone',
        label: 'Webhook',
        x: 266,
        y: 42,
        width: 218,
        height: 390,
        fill: '#eef4ff',
        stroke: '#7891c6',
        textColor: '#35527e',
      },
      {
        id: 'agent-core-zone',
        label: 'Agent Core',
        x: 504,
        y: 42,
        width: 366,
        height: 390,
        fill: '#f2f0ff',
        stroke: '#8980e0',
        textColor: '#4c43b1',
      },
      {
        id: 'manual-zone',
        label: 'Manual Approval',
        x: 890,
        y: 42,
        width: 202,
        height: 390,
        fill: '#eef7f3',
        stroke: '#78a287',
        textColor: '#2f6240',
      },
    ],
    nodes: [
      {
        id: 'hourly-sweep',
        label: 'Hourly Sweep',
        detail: 'new signals + stale pages',
        x: 56,
        y: 84,
        width: 160,
        height: 60,
        tone: 'signal',
      },
      {
        id: 'nightly-recompaction',
        label: 'Nightly Recompaction',
        detail: 'refresh dossiers',
        x: 56,
        y: 190,
        width: 160,
        height: 60,
        tone: 'memory',
      },
      {
        id: 'daily-digest-run',
        label: 'Daily Digest',
        detail: 'prepare leadership brief',
        x: 56,
        y: 296,
        width: 160,
        height: 60,
        tone: 'artifact',
      },
      {
        id: 'signal-webhook',
        label: 'Signal Webhook',
        detail: 'feedback / support / analytics',
        x: 294,
        y: 84,
        width: 160,
        height: 60,
        tone: 'signal',
      },
      {
        id: 'repo-webhook',
        label: 'Repo Webhook',
        detail: 'merged PR / release / incident',
        x: 294,
        y: 190,
        width: 160,
        height: 60,
        tone: 'metric',
      },
      {
        id: 'anomaly-webhook',
        label: 'Metric Alert',
        detail: 'funnel drop / churn spike',
        x: 294,
        y: 296,
        width: 160,
        height: 60,
        tone: 'metric',
      },
      {
        id: 'runtime-project-brain',
        label: 'Project Brain',
        detail: 'pages + sources + freshness',
        x: 540,
        y: 78,
        width: 152,
        height: 72,
        tone: 'memory',
      },
      {
        id: 'runtime-resolver',
        label: 'Resolver',
        detail: 'load task-specific context',
        x: 716,
        y: 88,
        width: 126,
        height: 52,
        tone: 'harness',
      },
      {
        id: 'runtime-hop-agent',
        label: 'Always-On HoP Agent',
        detail: 'triage / decide / draft',
        x: 614,
        y: 180,
        width: 160,
        height: 94,
        tone: 'agent',
      },
      {
        id: 'deterministic-guards',
        label: 'Deterministic Guards',
        detail: 'ROI / policy / blast radius',
        x: 540,
        y: 316,
        width: 152,
        height: 60,
        tone: 'foundation',
      },
      {
        id: 'auto-digest',
        label: 'Auto Outputs',
        detail: 'digest / refreshed backlog',
        x: 716,
        y: 314,
        width: 126,
        height: 64,
        tone: 'artifact',
      },
      {
        id: 'approve-brief',
        label: 'Approve Brief',
        detail: 'ship new recommendation',
        x: 914,
        y: 94,
        width: 154,
        height: 60,
        tone: 'artifact',
      },
      {
        id: 'approve-build',
        label: 'Approve Build',
        detail: 'enqueue implementation work',
        x: 914,
        y: 188,
        width: 154,
        height: 60,
        tone: 'artifact',
      },
      {
        id: 'approve-policy',
        label: 'Override / Veto',
        detail: 'raise threshold or redirect',
        x: 914,
        y: 282,
        width: 154,
        height: 60,
        tone: 'artifact',
      },
    ],
    edges: [
      {
        from: 'hourly-sweep',
        to: 'runtime-hop-agent',
        fromSide: 'right',
        toSide: 'left',
        label: 'wake',
        waypoints: [{ x: 516, y: 114 }, { x: 516, y: 227 }],
      },
      {
        from: 'nightly-recompaction',
        to: 'runtime-project-brain',
        fromSide: 'right',
        toSide: 'left',
        label: 'refresh',
        waypoints: [{ x: 516, y: 220 }, { x: 516, y: 114 }],
      },
      {
        from: 'daily-digest-run',
        to: 'auto-digest',
        fromSide: 'right',
        toSide: 'left',
        label: 'publish',
        waypoints: [{ x: 516, y: 326 }, { x: 700, y: 326 }],
      },
      {
        from: 'signal-webhook',
        to: 'runtime-hop-agent',
        fromSide: 'right',
        toSide: 'left',
        label: 'interrupt',
        waypoints: [{ x: 492, y: 114 }, { x: 492, y: 227 }],
      },
      {
        from: 'repo-webhook',
        to: 'runtime-project-brain',
        fromSide: 'right',
        toSide: 'left',
        label: 'update',
        waypoints: [{ x: 516, y: 220 }, { x: 516, y: 114 }],
      },
      {
        from: 'anomaly-webhook',
        to: 'runtime-hop-agent',
        fromSide: 'right',
        toSide: 'left',
        label: 'escalate',
        waypoints: [{ x: 492, y: 326 }, { x: 492, y: 227 }],
      },
      {
        from: 'runtime-project-brain',
        to: 'runtime-resolver',
        fromSide: 'right',
        toSide: 'left',
        label: 'resolve',
      },
      {
        from: 'runtime-resolver',
        to: 'runtime-hop-agent',
        fromSide: 'bottom',
        toSide: 'top',
      },
      {
        from: 'runtime-hop-agent',
        to: 'deterministic-guards',
        fromSide: 'bottom',
        toSide: 'top',
        label: 'score',
      },
      {
        from: 'deterministic-guards',
        to: 'auto-digest',
        fromSide: 'right',
        toSide: 'left',
        label: 'auto-safe',
      },
      {
        from: 'runtime-hop-agent',
        to: 'approve-brief',
        fromSide: 'right',
        toSide: 'left',
        label: 'new thesis',
        waypoints: [{ x: 860, y: 227 }, { x: 860, y: 124 }],
      },
      {
        from: 'runtime-hop-agent',
        to: 'approve-build',
        fromSide: 'right',
        toSide: 'left',
        label: 'material change',
      },
      {
        from: 'runtime-hop-agent',
        to: 'approve-policy',
        fromSide: 'right',
        toSide: 'left',
        tone: 'muted',
        dashed: true,
        label: 'conflict / risk',
        waypoints: [{ x: 860, y: 227 }, { x: 860, y: 312 }],
      },
      {
        from: 'approve-brief',
        to: 'runtime-project-brain',
        fromSide: 'left',
        toSide: 'right',
        tone: 'feedback',
        dashed: true,
        label: 'commit decision',
        waypoints: [{ x: 888, y: 124 }, { x: 888, y: 60 }, { x: 704, y: 60 }, { x: 704, y: 114 }],
      },
      {
        from: 'approve-build',
        to: 'auto-digest',
        fromSide: 'left',
        toSide: 'right',
        tone: 'feedback',
        dashed: true,
        label: 'queue packet',
        waypoints: [{ x: 888, y: 218 }, { x: 888, y: 346 }],
      },
      {
        from: 'approve-policy',
        to: 'deterministic-guards',
        fromSide: 'left',
        toSide: 'right',
        tone: 'feedback',
        dashed: true,
        label: 'retune gates',
        waypoints: [{ x: 888, y: 312 }, { x: 888, y: 392 }, { x: 704, y: 392 }, { x: 704, y: 346 }],
      },
    ],
  },
]

export function getBrainDiagram(slug: string): BrainDiagram {
  const diagram = BRAIN_DIAGRAMS.find((candidate) => candidate.slug === slug)

  if (!diagram) {
    throw new Error(`Unknown brain diagram: ${slug}`)
  }

  return diagram
}
