import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { getGitHubToken } from '@/lib/github/get-token'

export async function POST(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params

  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Get the GitHub provider token (session first, then DB fallback)
  const providerToken = await getGitHubToken()
  if (!providerToken) {
    return NextResponse.json({ error: 'No GitHub token. Re-login with GitHub.' }, { status: 400 })
  }

  const admin = createAdminClient()

  // Get roadmap item + project
  const { data: item } = await admin
    .from('roadmap_items')
    .select('*, projects(repo_url, name)')
    .eq('id', id)
    .single()

  if (!item) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 })
  }

  const project = item.projects as unknown as { repo_url: string | null; name: string }
  if (!project?.repo_url) {
    return NextResponse.json({ error: 'No repository connected' }, { status: 400 })
  }

  // Extract owner/repo
  const repoMatch = project.repo_url.match(/github\.com\/([^/]+\/[^/]+)/)
  if (!repoMatch) {
    return NextResponse.json({ error: 'Invalid repo URL' }, { status: 400 })
  }
  const repoFullName = repoMatch[1].replace(/\.git$/, '')

  // Build issue body from PRD
  const prd = item.prd_content as Record<string, unknown> | null
  const labels: string[] = []

  if (item.category === 'bug') labels.push('bug')
  else if (item.category === 'feature') labels.push('enhancement')
  else if (item.category === 'improvement') labels.push('improvement')

  let body = `## ${item.title}\n\n`
  body += `**Category:** ${item.category} | **Impact:** ${item.impact}/10 | **Size:** ${item.size}/10 | **ROI:** ${item.roi_score}\n\n`

  if (prd) {
    if (prd.problem) body += `### Problem\n${prd.problem}\n\n`
    if (prd.solution) body += `### Solution\n${prd.solution}\n\n`
    if (prd.acceptance_criteria && Array.isArray(prd.acceptance_criteria)) {
      body += `### Acceptance Criteria\n${(prd.acceptance_criteria as string[]).map(c => `- [ ] ${c}`).join('\n')}\n\n`
    }
    if (prd.files_to_modify && Array.isArray(prd.files_to_modify)) {
      body += `### Files to Modify\n${(prd.files_to_modify as Array<{ path: string; changes: string }>).map(f => `- \`${f.path}\`: ${f.changes}`).join('\n')}\n\n`
    }
    if (prd.test_requirements && Array.isArray(prd.test_requirements)) {
      body += `### Test Requirements\n${(prd.test_requirements as string[]).map(t => `- ${t}`).join('\n')}\n\n`
    }
    if (prd.rollback_plan) body += `### Rollback Plan\n${prd.rollback_plan}\n\n`
  } else {
    body += `${item.description}\n\n`
    if (item.acceptance_criteria && Array.isArray(item.acceptance_criteria)) {
      body += `### Acceptance Criteria\n${(item.acceptance_criteria as string[]).map(c => `- [ ] ${c}`).join('\n')}\n\n`
    }
  }

  body += `---\n*Generated by [SelfImprove](https://selfimprove-iota.vercel.app) — AI Product Manager*`

  // Create GitHub Issue
  try {
    const res = await fetch(`https://api.github.com/repos/${repoFullName}/issues`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${providerToken}`,
        Accept: 'application/vnd.github.v3+json',
        'User-Agent': 'SelfImprove-App',
      },
      body: JSON.stringify({
        title: item.title,
        body,
        labels,
      }),
    })

    if (!res.ok) {
      const err = await res.json()
      return NextResponse.json({ error: err.message || 'Failed to create issue' }, { status: res.status })
    }

    const issue = await res.json()

    // Store the issue URL on the roadmap item metadata
    const existingEvidence = (item.evidence_trail as unknown[]) || []
    await admin
      .from('roadmap_items')
      .update({
        evidence_trail: [
          ...existingEvidence,
          { type: 'github_issue', url: issue.html_url, number: issue.number },
        ],
      })
      .eq('id', id)

    return NextResponse.json({
      url: issue.html_url,
      number: issue.number,
    })
  } catch {
    return NextResponse.json({ error: 'GitHub API error' }, { status: 500 })
  }
}
