import { createAdminClient } from '@/lib/supabase/admin'

export async function createGitHubIssue(
  itemId: string,
  githubToken: string,
): Promise<{ url: string; number: number } | null> {
  const admin = createAdminClient()

  const { data: item } = await admin
    .from('roadmap_items')
    .select('*, projects(repo_url, name)')
    .eq('id', itemId)
    .single()

  if (!item) return null

  const project = item.projects as unknown as { repo_url: string | null; name: string }
  if (!project?.repo_url) return null

  const repoMatch = project.repo_url.match(/github\.com\/([^/]+\/[^/]+)/)
  if (!repoMatch) return null
  const repoFullName = repoMatch[1].replace(/\.git$/, '')

  const prd = item.prd_content as Record<string, unknown> | null
  const labels: string[] = []
  if (item.category === 'bug') labels.push('bug')
  else if (item.category === 'feature') labels.push('enhancement')
  else if (item.category === 'improvement') labels.push('improvement')

  let body = `## ${item.title}\n\n`
  body += `**Category:** ${item.category} | **Impact:** ${item.impact}/10 | **Size:** ${item.size}/10 | **ROI:** ${item.roi_score}\n\n`

  if (prd) {
    if (prd.problem) body += `### Problem\n${prd.problem}\n\n`
    if (prd.solution) body += `### Solution\n${prd.solution}\n\n`
    if (prd.acceptance_criteria && Array.isArray(prd.acceptance_criteria)) {
      body += `### Acceptance Criteria\n${(prd.acceptance_criteria as string[]).map(c => `- [ ] ${c}`).join('\n')}\n\n`
    }
    if (prd.files_to_modify && Array.isArray(prd.files_to_modify)) {
      body += `### Files to Modify\n${(prd.files_to_modify as Array<{ path: string; changes: string }>).map(f => `- \`${f.path}\`: ${f.changes}`).join('\n')}\n\n`
    }
    if (prd.test_requirements && Array.isArray(prd.test_requirements)) {
      body += `### Test Requirements\n${(prd.test_requirements as string[]).map(t => `- ${t}`).join('\n')}\n\n`
    }
    if (prd.rollback_plan) body += `### Rollback Plan\n${prd.rollback_plan}\n\n`
  } else {
    body += `${item.description}\n\n`
  }

  body += `---\n*Generated by [SelfImprove](https://selfimprove-iota.vercel.app) — AI Product Manager*`

  const res = await fetch(`https://api.github.com/repos/${repoFullName}/issues`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${githubToken}`,
      Accept: 'application/vnd.github.v3+json',
      'User-Agent': 'SelfImprove-App',
    },
    body: JSON.stringify({ title: item.title, body, labels }),
  })

  if (!res.ok) return null

  const issue = await res.json()

  const existingEvidence = (item.evidence_trail as unknown[]) || []
  await admin
    .from('roadmap_items')
    .update({
      evidence_trail: [
        ...existingEvidence,
        { type: 'github_issue', url: issue.html_url, number: issue.number },
      ],
    })
    .eq('id', itemId)

  return { url: issue.html_url, number: issue.number }
}
